#!/usr/bin/env bash

run_python_script() {
  if ! python3 setup/readiness_test.py; then
    exit 1
  fi
}

# Check if python3 command is available and Python version is 3.10 or greater
if command -v python3 &> /dev/null &&
   python_version=$(python3 -c "import sys; print(sys.version_info.major * 10 + sys.version_info.minor)") &&
   [[ $python_version -ge 40 ]]; then
  run_python_script
  else
    # If not, use nix-shell with Python 3.11
    nix-shell -p python311 --run "$(declare -f run_python_script); run_python_script"
fi