#!/usr/bin/env bash

echo "Installing Cardano Node and CLI..."

if [ ! -d $CARDANO_SRC_PATH ]; then
  mkdir $CARDANO_SRC_PATH
fi

cd $CARDANO_SRC_PATH

if [ ! -d "cardano-node" ]; then
    git clone "https://github.com/input-output-hk/cardano-node"
    cd "cardano-node"
  else
    cd "cardano-node"
    git fetch
fi

git reset --hard $NODE_RELEASE
nix build ".#$NETWORK/node"
nix-env -f . -iA cardano-node
nix build ".#cardano-cli"
nix-env -f . -iA cardano-cli

if [ ! -d "$CARDANO_PATH" ]; then
  if [ ! -d "$HOME/cardano" ]; then
    mkdir "$HOME/cardano"
  fi
  mkdir $CARDANO_PATH
  mkdir $DB_PATH
  mkdir $CONFIG_PATH
fi

cd $CONFIG_PATH

CONFIG_SRC_PATH="https://book.world.dev.cardano.org/environments/$TESTNET_NAME"

config_files=(
  "config"
  "db-sync-config"
  "submit-api-config"
  "topology"
  "alonzo-genesis"
  "byron-genesis"
  "shelley-genesis"
)

echo "Downloading config files..."
for file in "${config_files[@]}"
do
  curl -O -J "$CONFIG_SRC_PATH/$file.json"
done

echo "cardano-node and cardano-cli installed and configured successfully."
echo "Use 'run-node' command to start the node"