#!/usr/bin/env bash

if [ -z "$1" ]; then
    >&2 echo "expected policy name as argument"
    exit 1
fi

if [ -z "$2" ]; then
    >&2 echo "expected token name as argument"
    exit 1
fi

echo -n $(policyid $1).$(token-name $2)