#!/usr/bin/env bash

if [ -z "$1" ]; then
    >&2 echo "expected transaction name as argument"
    exit 1
fi

if [ -z "$2" ]; then
    >&2 echo "expected signer name as argument"
    exit 1
fi

tx="$TX_PATH/$1"
skeyfiles=""

for user in "${@:2}"; do
  skeyfiles+="--signing-key-file $KEYS_PATH/$user.skey "
done

cardano-cli transaction sign \
--tx-body-file "$tx.raw" \
$skeyfiles \
--out-file "$tx.signed"

if [ $? -eq 0 ]; then
  users=$(printf "%s, " "${@:2}")
  users="${users%, }"

  echo "Signed transaction '$1' for $users."
  echo "Wrote signed transaction to '$tx.signed'."
fi