#!/usr/bin/env bash

if [ -z "$1" ]; then
    >&2 echo "expected signer name as argument"
    exit 1
fi

if [ -z "$2" ]; then
    >&2 echo "expected transaction name as argument"
    exit 1
fi

skey="$KEYS_PATH/$1.skey"
tx="$TX_PATH/$2"

cardano-cli transaction sign \
--signing-key-file $skey \
--tx-body-file "$tx.raw" \
--out-file "$tx.signed" \
$NET