#!/usr/bin/env bash

if [ -z "$1" ]; then
    >&2 echo "expected signer name as argument"
    exit 1
fi

if [ -z "$2" ]; then
    >&2 echo "expected transaction name as argument"
    exit 1
fi

cardano-cli transaction witness \
--signing-key-file "$KEYS_PATH/$1.skey" \
--tx-body-file "$TX_PATH/$2.raw" \
--out-file "$TX_PATH/$2-$1.witness" \
$NET