#!/usr/bin/env bash

if [ -n "$3" ]; then
  nix run . --accept-flake-config --no-warn-dirty -- "$1" "$2" "$3"
else
  if [ -n "$2" ]; then
    nix run . --accept-flake-config --no-warn-dirty -- "$1" "$2"
  else
    nix run . --accept-flake-config --no-warn-dirty -- "$1"
  fi
fi