#!/usr/bin/env bash

if [ -n "$1" ] && [ -d "$1" ]; then
    target_directory="$1"
elif [ -n "$1" ]; then
    echo "Invalid directory: $1"
    exit 1
else
    target_directory="."
fi

if [[ "$VIM_MODE" == "true" ]]; then
    codium "$target_directory"
else
    codium "$target_directory" --disable-extension asvetliakov.vscode-neovim
fi