#!/usr/bin/env bash

cardano-node run \
  --topology $CONFIG_PATH/topology.json \
  --database-path $CARDANO_PATH/db \
  --socket-path $CARDANO_NODE_SOCKET_PATH \
  --port 1337 \
  --config $CONFIG_PATH/config.json