#!/usr/bin/env bash

dir=$(find dist-newstyle/src -type d -name 'plutus-ap_*' -print -quit)

if [ -n "$dir" ]; then
  cd "dist-newstyle/src/$(basename "$dir")"
  nix develop --command "serve-docs"
else
  echo "Error: plutus-apps directory not found"
fi