#!/usr/bin/env bash

python3 cardano-ez-installer/main.py

if [ $? -eq 0 ]; then
  source ~/.bashrc
  read -p "Clean up nix-store? [Y/n] " answer
  answer=${answer:-Y}

  if [[ $answer =~ ^[Yy]$ ]]
  then
    nix-collect-garbage -d
  fi
fi